server:
  port: ${PORT:8080}

api:
  database:
    name: desafio_agrotis
    host: 127.0.0.1
    port: 5432
    username: desafio
    password: desafio

spring:
  application:
    name: desafio-api-agrotis

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${api.database.host}:${api.database.port}/${api.database.name}
    password: ${api.database.password}
    username: ${api.database.username}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false


logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
